server {
    listen 8085;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Redirection HTTP -> HTTPS (via le reverse proxy)
    if ($http_x_forwarded_proto = "http") {
        return 301 https://$host$request_uri;
    }

    location = /admin   { try_files /admin.html   =404; }
    location = /profile { try_files /profile.html =404; }

    # Pas de cache sur HTML et JS (forcer rechargement)
    location ~* \.(html|js)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        try_files $uri =404;
    }

    # Fichiers statiques
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy → dgames-auth
    location /api/auth/ {
        proxy_pass         http://dgames-auth:8001/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_pass_header  Set-Cookie;
    }

    # Proxy → dgames-api  (/api/games et /api/games/... → dgames-api:8000/...)
    location ~ ^/api/games(/|$) {
        rewrite            ^/api/games/?(.*)$ /$1 break;
        proxy_pass         http://dgames-api:8000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_pass_header  Cookie;
    }
}
